spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabricio-entringer/spring-lab
          default-label: master
          basedir: config

server:
  port: 9999
